all:
	g++ -std=c++17 -O2 -Wall -pedantic -pthread -fconcepts quick_sort.cpp -o quick_sort
	g++ -std=c++17 -O2 -Wall -pedantic -pthread -fconcepts merge_sort.cpp -o merge_sort
	g++ -std=c++17 -O2 -Wall -pedantic -pthread -fconcepts insertion_sort.cpp -o insertion_sort
        
clean:
	rm -rf quick_sort merge_sort insertion_sort
